id: I4414DD12
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:44:13+00:00'
last_modified: '2022-06-07T20:38:39.160179+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18766
  title: ཟུར་ཞིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '8860':
      image_group_id: I1KG20679
      title: ''
      total_pages: 300
      order: 1
      base_file: 8860.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
