id: P004153
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:56:49.494708
source_metadata:
  id: bdr:W1KG18766
  title: ཟུར་ཞིག
  author: ''
  volumes:
    b0f20dcb38ba4fe2bc3b553a3bd083e2:
      image_group_id: I1KG20679
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
